[package]
name = "bevy_starling"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
bevy = { workspace = true }
serde = { workspace = true }
ron = { workspace = true }
thiserror = { workspace = true }
